### ISSUE TITLE
[item] Argent Pony Bridle, Argent Squire, Argent Gruntling

### ISSUE THREAD

**Issue by GalaxyWoW** [tkrokli/TrinityCore#2] opened 2015-04-26 06:04 UTC
(this issue was open so I just copied the text)

The item [[Argent Pony Bridle](http://www.wowhead.com/item=47541/argent-pony-bridle)] is bugged , when you click on it you should get these options :

- Bank
- Trader (vendor)
- Mailbox

But you can't see that list, you just see Trader (vendor). In addition the item "Argent Pony Bridle" which should provide a mount for this companion doesn't work either.

Related IDs:
http://www.wowhead.com/item=44998/argent-squire
http://www.wowhead.com/item=45022/argent-gruntling
http://www.wowhead.com/item=47541/argent-pony-bridle

**Comment by tkrokli** [comment] 2015-04-26 16:31
Thanks, but since the issue is an open one on the TrinityCore issue tracker, I will only keep this as a tracking issue for later follow-up. I don't have the C++ skills to fix this issue myself, since it needs blizzlike scripting for the 4 hour cooldown part to work.

**Comment by tkrokli** [comment] 2015-05-20 06:10
https://github.com/TrinityCore/TrinityCore/commit/64bed16a5761ee98da5386575ae39f237a8721d3 may be the solution to this issue.

**Comment by tkrokli** [comment] 2016-08-30 06:44
Closed in PR https://github.com/TrinityCore/TrinityCore/pull/17789 (commit https://github.com/TrinityCore/TrinityCore/commit/989aaaa8b5284bc707c94c62e6c50e9df3cbfc84)

**Closed by tkrokli** 2016-08-30 06:44 UTC
Labels: bug, duplicate
